services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crud_app

    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
      

  backend:
    image: rajatrulaniya/devsecops-backend:latest
    container_name: backend-api`
    
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: crud_app
      JWT_SECRET: devopsexampleSuperSecretKey
      RESET_ADMIN_PASS: 'true'
      PORT: 5000

    ports:
      - "5000:5000"
    
    depends_on: 
      - mysql


  frontend:
    image: rajatrulaniya/devsecops-frontend:latest
    container_name: frontend-client
    
    depends_on: 
      - backend

    ports:
      - "3000:80"
  
volumes:
  mysql-data: